// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmMiw7XaX1SrClitam2LA0IBDytxL3Jk',
    appId: '1:499532365198:web:75e3b0f458ab28f033b8df',
    messagingSenderId: '499532365198',
    projectId: 'iphone-study',
    authDomain: 'iphone-study.firebaseapp.com',
    storageBucket: 'iphone-study.appspot.com',
    measurementId: 'G-3J3G8D6L3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMuJLpIcIAk0NeKyukAT_pIlnJ1D693c0',
    appId: '1:499532365198:android:34c568b8c03e762233b8df',
    messagingSenderId: '499532365198',
    projectId: 'iphone-study',
    storageBucket: 'iphone-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_XIHVlHw4IyFQbrSZyNj21U6AHtMfV0',
    appId: '1:499532365198:ios:bac535bbd11d37ef33b8df',
    messagingSenderId: '499532365198',
    projectId: 'iphone-study',
    storageBucket: 'iphone-study.appspot.com',
    iosBundleId: 'com.example.iphoneStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe_XIHVlHw4IyFQbrSZyNj21U6AHtMfV0',
    appId: '1:499532365198:ios:7bf9ab4b5a91bd5933b8df',
    messagingSenderId: '499532365198',
    projectId: 'iphone-study',
    storageBucket: 'iphone-study.appspot.com',
    iosBundleId: 'com.example.iphoneStudyApp.RunnerTests',
  );
}
